#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    # -J|--remote-header-name forces curl to use the filename from the server
    cd $2; curl -L -f -J -O $PROXY $1; cd -
}

# Always download latest version
#URL="https://sourceforge.net/projects/phplist/files/latest/download"

# we have to download 3.6.7 explicitly as the sourceforge latest hasn't been
# updated for a while and installs an older RC

URL="https://sourceforge.net/projects/phplist/files/phplist/3.6.14/phplist-3.6.14.zip/download"

dl $URL /usr/local/src

