#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    # -J|--remote-header-name forces curl to use the filename from the server
    cd $2; curl -L -f -J -O $PROXY $1; cd -
}

# Always download latest version
URL="https://sourceforge.net/projects/phplist/files/latest/download"

dl $URL /usr/local/src

