#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    # -J|--remote-header-name forces curl to use the filename from the server
    cd $2; curl -L -f -J -O $PROXY $1; cd -
}

# Pull download link for latest version from downloads page
URL=$(curl https://www.phplist.org/download-phplist/ \
        | sed -En '\|Download ZIP|s|^.* href="(http[a-z0-9\.:/-]+)">.*$|\1|p')

dl $URL /usr/local/src

