#!/bin/bash -e
# regenerate phplist mysql password

. /etc/default/inithooks

PASSWORD=$(mcookie)

CONF=/var/www/phplist/config/config.php

sed -i "s/\$database_password = \(.*\)/\$database_password = \'$PASSWORD\';/" $CONF

$INITHOOKS_PATH/bin/mysqlconf.py --user=phplist --pass="$PASSWORD"

